export enum ErrorEnum {
  // 模块码（0-9）+条数（01-99）
  DEFAULT = '0:未知错误',
  SERVER_ERROR = '500:服务繁忙，请稍后再试',
  // 用户模块
  SYSTEM_USER_EXISTS = '101:系统用户已存在',
  INVALID_VERIFICATION_CODE = '102:验证码填写有误',
  INVALID_USERNAME_PASSWORD = '103:用户名密码有误',
  NODE_ROUTE_EXISTS = '104:节点路由已存在',
  PERMISSION_REQUIRES_PARENT = '105:权限必须包含父节点',
  ILLEGAL_OPERATION_DIRECTORY_PARENT = '106:非法操作：该节点仅支持目录类型父节点',
  ILLEGAL_OPERATION_CANNOT_CONVERT_NODE_TYPE = '107:非法操作：节点类型无法直接转换',
  ROLE_HAS_ASSOCIATED_USERS = '108:该角色存在关联用户，请先删除关联用户',
  DEPARTMENT_HAS_ASSOCIATED_USERS = '109:该部门存在关联用户，请先删除关联用户',
  DEPARTMENT_HAS_ASSOCIATED_ROLES = '110:该部门存在关联角色，请先删除关联角色',
  PASSWORD_MISMATCH = '111:旧密码与原密码不一致',
  LOGOUT_OWN_SESSION = '112:如想下线自身可右上角退出',
  NOT_ALLOWED_TO_LOGOUT_USER = '113:不允许下线该用户',
  PARENT_MENU_NOT_FOUND = '114:父级菜单不存在',
  DEPARTMENT_HAS_CHILD_DEPARTMENTS = '115:该部门存在子部门，请先删除子部门',
  SYSTEM_BUILTIN_FUNCTION_NOT_ALLOWED = '116:系统内置功能不允许操作',
  USER_NOT_FOUND = '117:用户不存在',
  USER_NAME_EXIST = '118:用户名已存在',
  UNABLE_TO_FIND_DEPARTMENT_FOR_USER = '119:无法查找当前用户所属部门',
  DEPARTMENT_NOT_FOUND = '120:部门不存在',
  PARAMETER_CONFIG_KEY_EXISTS = '122:参数配置键值对已存在',
  DEFAULT_ROLE_NOT_FOUND = '123:所分配的默认角色不存在',

  INVALID_LOGIN = '111:登录无效，请重新登录',
  NO_PERMISSION = '112:无权限访问',
  ONLY_ADMIN_CAN_LOGIN = '113:不是管理员，无法登录',
  REQUEST_INVALIDATED = '114:当前请求已失效',
  ACCOUNT_LOGGED_IN_ELSEWHERE = '115:您的账号已在其他地方登录',
  GUEST_ACCOUNT_RESTRICTED_OPERATION = '116:游客账号不允许操作',
  REQUESTED_RESOURCE_NOT_FOUND = '117:所请求的资源不存在',
  OLDPASSWORD_FALSE = '118:旧密码错误',
  DATA_DUPLICATE = '119:数据重复',

  // 验证码模块
  TOO_MANY_REQUESTS = '201:请求频率过快，请一分钟后再试',
  MAXIMUM_FIVE_VERIFICATION_CODES_PER_DAY = '202:一天最多发送5条验证码',
  VERIFICATION_CODE_SEND_FAILED = '203:验证码发送失败',
  // 任务模块
  INSECURE_MISSION = '301:不安全的任务，确保执行的加入@Mission注解',
  EXECUTED_MISSION_NOT_FOUND = '302:所执行的任务不存在',
  MISSION_EXECUTION_FAILED = '303:任务执行失败',
  MISSION_NOT_FOUND = '304:任务不存在',
  // OSS模块
  OSS_FILE_OR_DIR_EXIST = '401:当前创建的文件或目录已存在',
  OSS_NO_OPERATION_REQUIRED = '402:无需操作',
  OSS_EXCEE_MAXIMUM_QUANTITY = '403:已超出支持的最大处理数量',
  OSS_NO_FILE = '404:没有提供文件',
  OSS_MIME_AND_EXT_REQUIRED = '412:MIME类型和文件扩展名都是必需的',
  OSS_EXTENSION_REQUIRED = '413:请提供文件扩展名',
  OSS_MIME_TYPE_REQUIRED = '414:请提供MIME类型',
  OSS_EXTENSION_OR_MIME_REQUIRED = '415:请提供扩展名或MIME类型',
  OSS_FILE_TYPE_NAME_EXISTS = '416:文件类型名称已存在',
  OSS_FILE_TYPE_IN_USE = '417:文件类型已被文件使用，无法删除',
  OSS_ROLE_ASSOCIATION_EXISTS = '418:文件类型与角色的关联已存在',
  OSS_PREDEFINED_CATEGORY_NOT_FOUND = '419:预定义分类不存在',

  // 包装模块
  PACKAGE_NOT_FOUND = '501:包装不存在',
  PACKAGE_NAME_EXISTS = '502:包装名称已存在',
  PACKAGE_IN_USE = '503:该包装正在被使用，不能删除',
  PACKAGE_INVALID_SIZE = '504:包装尺寸不能为负数',
  PACKAGE_INVALID_CONTAINER_QUANTITY = '505:集装箱可装数量不能为负数',

  // 标签模块
  TAG_NOT_FOUND = '601:标签不存在',
  TAG_NAME_EXISTS = '602:标签名称已存在',
  TAG_IN_USE = '603:该标签正在被使用，不能删除',

  // 分类模块
  CATEGORY_NOT_FOUND = '701:分类不存在',
  CATEGORY_NAME_EXISTS = '702:分类名称已存在',
  CATEGORY_IN_USE = '703:该分类正在被使用，不能删除',
  CATEGORY_HAS_CHILDREN = '704:该分类下有子分类，不能删除',

  // 产品模块
  ITEM_NOT_FOUND = '801:产品不存在',
  ITEM_CATEGORY_NOT_FOUND = '802:产品分类不存在',
  ITEM_SPU_NOT_FOUND = '803:SPU不存在',
  ITEM_SPU_IN_USE = '804:该SPU已被使用',
  ITEM_COMBINATION_NOT_FOUND = '805:套餐不存在',
  ITEM_COMBINATION_IN_USE = '806:该套餐已被使用',
  ITEM_INVALID_TYPE = '807:产品不能同时关联SPU和套餐',
  ITEM_TYPE_REQUIRED = '808:产品必须关联SPU或套餐',
  ITEM_SKU_NOT_FOUND = '809:SKU不存在',
  ITEM_SKU_IN_USE = '810:该SKU已被使用',
  ITEM_INVALID_DISCOUNT = '811:折扣必须在0到1之间',
  ITEM_INVALID_QUANTITY = '812:数量必须大于0',
  ITEM_INVALID_PRICE = '813:价格必须大于0',
  ITEM_TAG_NOT_FOUND = '814:标签不存在',
  ITEM_SKU_HIDDEN = '815:该SKU已被隐藏，不能添加到套餐中',
  ITEM_SKU_IN_COMBINATION = '816:该SKU已在套餐中',
  ITEM_COMBINATION_SKU_NOT_FOUND = '817:套餐中不存在该SKU',
  ITEM_NOT_SPU_TYPE = '818:该产品不是SPU类型',
  ITEM_NOT_COMBINATION_TYPE = '819:该产品不是套餐类型',
  ITEM_DISCOUNT_RANGE = '820:折扣必须在0到1之间',
  ITEM_SKU_ALREADY_IN_COMBINATION = '821:该SKU已在套餐中',
  ITEM_SKU_NOT_IN_COMBINATION = '822:该SKU不在套餐中',

  // 新增错误码
  ITEM_SKU_IMAGE_NOT_FOUND = '824:SKU图片关联不存在',
  ITEM_SKU_ATTACHMENT_NOT_FOUND = '825:SKU附件关联不存在',
  ITEM_SKU_3D_MODEL_NOT_FOUND = '826:SKU 3D模型关联不存在',
  ITEM_COMBINATION_IMAGE_NOT_FOUND = '827:套餐图片关联不存在',
  ITEM_INVALID_3D_MODEL_FORMAT = '828:文件不是有效的3D模型格式',

  FUNCTION_NOT_FOUND = '900:功能不存在',
  PARAM_NOT_FOUND = '901:参数不存在',

  // OSS文件链接相关错误码
  OSS_INVALID_EXPIRY_TIME = '420:无效的链接过期时间，必须大于0',
  OSS_URL_GENERATION_FAILED = '421:生成文件链接失败',
  OSS_INVALID_USE_CASE = '422:无效的使用场景，请使用preview、download或longterm',
  OSS_MISSING_PARAMETERS = '423:请提供useCase(preview/download/longterm)或customExpiry参数指定URL有效期',

  // OSS相关错误
  OSS_FILE_NOT_FOUND = '60001:文件不存在',
  OSS_UPLOAD_FAILED = '60002:文件上传失败',
  OSS_FILE_TYPE_NOT_SUPPORT = '60003:不支持的文件类型',
  OSS_FILE_SIZE_EXCEED = '60004:文件大小超出限制',
  OSS_FILE_NOT_FOUND_IN_CLOUD = '60005:云端文件不存在',
  OSS_INVALID_MIME_TYPE = '60006:无效的MIME类型',
  OSS_INVALID_EXTENSION = '60007:无效的文件扩展名',
  OSS_FILE_TYPE_NOT_FOUND = '60008:文件类型未找到',
  OSS_FILE_TYPE_MATCH_FAILED = '60009:未找到匹配的文件类型，请手动选择',
  OSS_FILE_VALIDATION_FAILED = '60010:文件验证失败',
  OSS_INVALID_FILE_TYPE_ID = '60011:无效的文件类型ID',
  OSS_FILE_IN_USE = '60012:文件正在被使用',
}
